name: AI NOTES APP

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./ai-notes-app/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./ai-notes-app/terraform
        run: terraform apply -auto-approve

      - name: Get Terraform Outputs
        id: tf_outputs
        working-directory: ./ai-notes-app/terraform
        run: |
          echo "ECR_REPO_URL=$(terraform output -raw ecr_repo_url)" >> $GITHUB_ENV
          echo "RDS_ENDPOINT=$(terraform output -raw rds_endpoint)" >> $GITHUB_ENV
          echo "BUCKET_NAME=$(terraform output -raw bucket_name)" >> $GITHUB_ENV
          echo "EXECUTION_ROLE_ARN=$(terraform output -raw ecs_task_execution_role_arn)" >> $GITHUB_ENV

      - name: Replace placeholders in ecs-task-def.json
        run: |
          sed -i "s|<ECR_REPO_URL>|${{ env.ECR_REPO_URL }}|" ai-notes-app/ecs-task-def.json
          sed -i "s|<RDS_ENDPOINT>|${{ env.RDS_ENDPOINT }}|" ai-notes-app/ecs-task-def.json
          sed -i "s|<BUCKET_NAME>|${{ env.BUCKET_NAME }}|" ai-notes-app/ecs-task-def.json
          sed -i "s|<EXECUTION_ROLE_ARN>|${{ env.EXECUTION_ROLE_ARN }}|" ai-notes-app/ecs-task-def.json

      - name: Debug - Show updated task definition
        run: cat ai-notes-app/ecs-task-def.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          ECR_REPOSITORY: ai-notes-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f ai-notes-app/Dockerfile ai-notes-app
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ai-notes-app/ecs-task-def.json  # ✅ CORRECT PATH!
          cluster: ai-notes-cluster
          service: ai-notes-app-service
          wait-for-service-stability: true
