name: Deploy Azure Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        working-directory: ./AzurePipelineMigrationTool/terraform
        run: terraform init

      - name: Apply Terraform
        working-directory: ./AzurePipelineMigrationTool/terraform
        run: terraform apply -auto-approve

      - name: Get EC2 Public IP
        id: get_ip
        working-directory: ./AzurePipelineMigrationTool/terraform
        run: |
          echo "Extracting EC2 IP..."
          RAW_IP=$(terraform output -raw ec2_public_ip)
          echo "raw_ip=$RAW_IP" >> $GITHUB_OUTPUT
          echo "::notice::EC2 Public IP is $RAW_IP"

      - name: Set EC2 IP as Environment Variable
        run: echo "EC2_PUBLIC_IP=${{ steps.get_ip.outputs.raw_ip }}" >> "$GITHUB_ENV"

      - name: Wait for EC2 to be ready
        run: sleep 60

      - name: Copy app to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "./AzurePipelineMigrationTool"
          target: "/home/ec2-user/"

      - name: Deploy Docker app on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/AzurePipelineMigrationTool
            docker build -t azure-pipeline-migrator .
            docker stop azure-pipeline-migrator || true
            docker rm azure-pipeline-migrator || true
            docker run -d --name azure-pipeline-migrator -p 5000:5000 azure-pipeline-migrator
