name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: List repo root files
      run: ls -la

    - name: List API directory contents
      run: ls -la API

    - name: Install backend dependencies
      run: |
        cd API/backend
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backend tests (placeholder)
      run: |
        echo "Add your backend tests here"
        # cd API/backend
        # pytest tests/

    - name: Install frontend dependencies
      run: |
        cd API/frontend
        npm install

    - name: Run frontend tests (placeholder)
      run: |
        cd API/frontend
        npm test || echo "No frontend tests configured"

    - name: Build Docker images
      run: |
        cd API
        docker-compose build

    - name: Push Docker images (placeholder)
      run: |
        echo "Add your Docker push commands here"
        # docker login ...
        # docker push ...
