name: CI/CD → Terraform Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout python-todo-app folder only
      uses: actions/checkout@v3
      with:
        # Checkout the repo, but fetch only the python-todo-app folder
        # Note: GitHub Actions does not support partial checkout by default,
        # but you can do sparse checkout like this:
        fetch-depth: 1
        # We'll enable sparse checkout next
        sparse-checkout: python-todo-app/

    - name: Configure sparse checkout
      run: |
        git sparse-checkout init --cone
        git sparse-checkout set python-todo-app

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/python-todo-app:${{ github.sha }} -f python-todo-app/Dockerfile python-todo-app

    - name: Push Docker Image to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/python-todo-app:${{ github.sha }}

    - name: Install Terraform
      run: |
        sudo apt update && sudo apt install -y unzip curl gnupg software-properties-common
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
        | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update && sudo apt install terraform -y

    - name: Terraform Init and Apply
      working-directory: ./terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_private_key_path: /home/runner/.ssh/ec2.pem
        TF_VAR_key_name: ${{ secrets.EC2_KEY_NAME }}
        TF_VAR_docker_image: ${{ secrets.DOCKER_USERNAME }}/python-todo-app:${{ github.sha }}
      run: |
        terraform init
        terraform apply -auto-approve
