jobs:
  terraform:
    strategy:
      matrix:
        dir: [terraform, ec2_alarm]  # Add all terraform folders here

    runs-on: ubuntu-latest
    name: Terraform - ${{ matrix.dir }}
    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
