name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # AWS credentials setup
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Terraform steps
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: K8s-Flask-App-Project/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: K8s-Flask-App-Project/terraform
        run: terraform apply -auto-approve

      # Docker build and push
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-k8s:latest -f K8s-Flask-App-Project/Dockerfile K8s-Flask-App-Project
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-k8s:latest

      # EKS kubeconfig setup
      - name: Set up kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name my-cluster --region ${{ secrets.AWS_REGION }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.28.0

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f K8s-Flask-App-Project/kubernetes/deployment.yaml
          kubectl apply -f K8s-Flask-App-Project/kubernetes/service.yaml
