name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-k8s:latest -f K8s-Flask-App-Project/Dockerfile K8s-Flask-App-Project
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-k8s:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.28.0

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f K8s-Flask-App-Project/kubernetes/deployment.yaml
          kubectl apply -f K8s-Flask-App-Project/kubernetes/service.yaml
