name: Deploy StreamFlix App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      INSTANCE_KEY_FILE: my_key.pem

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./StreamFlix/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./StreamFlix/terraform

      - name: Get EC2 Public IP and Save
        run: |
          IP=$(terraform -chdir=./StreamFlix/terraform output -raw ec2_public_ip)
          echo "EC2_PUBLIC_IP=$IP" >> $GITHUB_ENV

      - name: Save EC2 Private Key to File
        run: |
          echo "${{ secrets.INSTANCE_KEY }}" > $INSTANCE_KEY_FILE
          chmod 400 $INSTANCE_KEY_FILE

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ env.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Copy App Files to EC2
        run: |
          scp -i $INSTANCE_KEY_FILE -o StrictHostKeyChecking=no -r ./app ec2-user@${{ env.EC2_PUBLIC_IP }}:/home/ec2-user/app

      - name: SSH into EC2 and Run Docker App
        run: |
          ssh -i $INSTANCE_KEY_FILE ec2-user@${{ env.EC2_PUBLIC_IP }} << EOF
          sudo yum update -y
          sudo yum install -y docker git python3
          sudo systemctl start docker
          sudo usermod -aG docker ec2-user
          cd /home/ec2-user/app
          docker build -t streamflix-app .
          docker run -d -p 80:5000 streamflix-app
          EOF
