name: Deploy StreamFlix App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1
      INSTANCE_KEY: my_key.pem

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Get EC2 IP
        id: get_ip
        run: |
          IP=$(terraform -chdir=./terraform output -raw ec2_public_ip)
          echo "EC2_IP=$IP" >> $GITHUB_ENV
          echo "$IP" > ec2_ip.txt

      - name: Create SSH Known Hosts File
        run: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts

      - name: Add EC2 Host to Known Hosts
        run: ssh-keyscan -H ${{ env.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Copy Files to EC2
        run: |
          chmod 400 ${INSTANCE_KEY}
          scp -i ${INSTANCE_KEY} -r ./app ec2-user@${{ env.EC2_IP }}:/home/ec2-user/app

      - name: SSH into EC2 and Run App
        run: |
          ssh -i ${INSTANCE_KEY} ec2-user@${{ env.EC2_IP }} << EOF
          sudo yum update -y
          sudo yum install -y docker git python3
          sudo systemctl start docker
          sudo usermod -aG docker ec2-user
          cd /home/ec2-user/app
          docker build -t streamflix-app .
          docker run -d -p 80:5000 streamflix-app
          EOF
