name: Deploy StreamFlix App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./StreamFlix/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./StreamFlix/terraform

      - name: Get EC2 IP
        id: get_ip
        run: |
          EC2_IP=$(terraform -chdir=./terraform output -raw ec2_public_ip)
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV
          echo "$EC2_IP" > ec2_ip.txt

      - name: Write EC2 Private Key to File
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Create SSH Known Hosts File
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Copy Files to EC2
        run: |
          scp -i private_key.pem -r ./app ec2-user@${{ env.EC2_IP }}:/home/ec2-user/app

      - name: SSH into EC2 and Run Docker App
        run: |
          ssh -i private_key.pem ec2-user@${{ env.EC2_IP }} << 'EOF'
            sudo yum update -y
            sudo yum install -y docker git python3
            sudo systemctl start docker
            sudo usermod -aG docker ec2-user
            cd /home/ec2-user/app
            sudo docker stop streamflix-app || true
            sudo docker rm streamflix-app || true
            sudo docker build -t streamflix-app .
            sudo docker run -d -p 80:5000 --name streamflix-app streamflix-app
          EOF
