name: Deploy Tic Tac Toe

on:
  push:
    
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init and Apply
      working-directory: ./tic-tac-toe-project/terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: |
        terraform init
        terraform apply -auto-approve -var="key_name=my_key"

    - name: Get EC2 Public IP from Terraform Output
      id: get_ip
      working-directory: ./tic-tac-toe-project/terraform
      run: |
        echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT

    - name: Build and Push Docker image
      working-directory: ./tic-tac-toe-project
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/tictactoe:latest .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/tictactoe:latest

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.get_ip.outputs.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.MY_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/tictactoe:latest
          docker stop $(docker ps -q) || true
          docker run -d -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/tictactoe:latest
